// <auto-generated />
using System;
using DUPSS.API.Models.AccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DUPSS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250701092529_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DUPSS.API.Models.Objects.Appointment", b =>
                {
                    b.Property<string>("AppointmentId")
                        .HasColumnType("text");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConsultantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("ConsultantId");

                    b.HasIndex("MemberId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.AssessmentLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("AssessmentLanguages");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.AssessmentResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<string>("RespondentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RiskLevel")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId");

                    b.ToTable("AssessmentResponses");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.AssessmentVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.ToTable("AssessmentVersions");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.Blog", b =>
                {
                    b.Property<string>("BlogId")
                        .HasColumnType("text");

                    b.Property<string>("BlogTopicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("BlogId");

                    b.HasIndex("BlogTopicId");

                    b.HasIndex("StaffId");

                    b.ToTable("Blog");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.BlogTopic", b =>
                {
                    b.Property<string>("BlogTopicId")
                        .HasColumnType("text");

                    b.Property<string>("BlogTopicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("BlogTopicId");

                    b.ToTable("BlogTopic");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.Campaign", b =>
                {
                    b.Property<string>("CampaignId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Introduction")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("CampaignId");

                    b.HasIndex("StaffId");

                    b.ToTable("Campaign");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.CampaignRegistration", b =>
                {
                    b.Property<string>("RegistrationId")
                        .HasColumnType("text");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RegistrationId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("MemberId");

                    b.ToTable("CampaignRegistrations");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .HasColumnType("text");

                    b.Property<string>("ConsultantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CourseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TopicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CourseId");

                    b.HasIndex("ConsultantId");

                    b.HasIndex("StaffId");

                    b.HasIndex("TopicId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.CourseEnroll", b =>
                {
                    b.Property<string>("EnrollId")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("CompleteDate")
                        .HasColumnType("date");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EnrollDate")
                        .HasColumnType("date");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EnrollId");

                    b.HasIndex("CourseId");

                    b.HasIndex("MemberId");

                    b.ToTable("CourseEnroll");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.CourseTopic", b =>
                {
                    b.Property<string>("TopicId")
                        .HasColumnType("text");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TopicId");

                    b.ToTable("CourseTopic");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.QuestionResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentResponseId")
                        .HasColumnType("integer");

                    b.Property<int?>("NumericResponse")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int?>("SelectedOptionId")
                        .HasColumnType("integer");

                    b.Property<string>("TextResponse")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentResponseId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.ToTable("QuestionResponses");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DoB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("refreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("refreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.Appointment", b =>
                {
                    b.HasOne("DUPSS.API.Models.Objects.User", "Consultant")
                        .WithMany("ConsultantAppointments")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUPSS.API.Models.Objects.User", "Member")
                        .WithMany("MemberAppointments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.AssessmentLanguage", b =>
                {
                    b.HasOne("DUPSS.API.Models.Objects.AssessmentVersion", "Version")
                        .WithMany("Languages")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.AssessmentResponse", b =>
                {
                    b.HasOne("DUPSS.API.Models.Objects.AssessmentLanguage", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUPSS.API.Models.Objects.User", null)
                        .WithMany("AssessmentResponses")
                        .HasForeignKey("UserId");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.AssessmentVersion", b =>
                {
                    b.HasOne("DUPSS.API.Models.Objects.Assessment", "Assessment")
                        .WithMany("Versions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.Blog", b =>
                {
                    b.HasOne("DUPSS.API.Models.Objects.BlogTopic", "BlogTopic")
                        .WithMany("Blogs")
                        .HasForeignKey("BlogTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUPSS.API.Models.Objects.User", "Staff")
                        .WithMany("Blogs")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogTopic");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.Campaign", b =>
                {
                    b.HasOne("DUPSS.API.Models.Objects.User", "Staff")
                        .WithMany("Campaigns")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.CampaignRegistration", b =>
                {
                    b.HasOne("DUPSS.API.Models.Objects.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUPSS.API.Models.Objects.User", "User")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.Course", b =>
                {
                    b.HasOne("DUPSS.API.Models.Objects.User", "Consultant")
                        .WithMany()
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUPSS.API.Models.Objects.User", "Staff")
                        .WithMany("Courses")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUPSS.API.Models.Objects.CourseTopic", "Topic")
                        .WithMany("Courses")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultant");

                    b.Navigation("Staff");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.CourseEnroll", b =>
                {
                    b.HasOne("DUPSS.API.Models.Objects.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUPSS.API.Models.Objects.User", "Member")
                        .WithMany("Enrollments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.Question", b =>
                {
                    b.HasOne("DUPSS.API.Models.Objects.AssessmentLanguage", "Language")
                        .WithMany("Questions")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.QuestionOption", b =>
                {
                    b.HasOne("DUPSS.API.Models.Objects.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.QuestionResponse", b =>
                {
                    b.HasOne("DUPSS.API.Models.Objects.AssessmentResponse", "AssessmentResponse")
                        .WithMany("Responses")
                        .HasForeignKey("AssessmentResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUPSS.API.Models.Objects.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUPSS.API.Models.Objects.QuestionOption", "SelectedOption")
                        .WithMany()
                        .HasForeignKey("SelectedOptionId");

                    b.Navigation("AssessmentResponse");

                    b.Navigation("Question");

                    b.Navigation("SelectedOption");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.User", b =>
                {
                    b.HasOne("DUPSS.API.Models.Objects.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.Assessment", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.AssessmentLanguage", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.AssessmentResponse", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.AssessmentVersion", b =>
                {
                    b.Navigation("Languages");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.BlogTopic", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.CourseTopic", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DUPSS.API.Models.Objects.User", b =>
                {
                    b.Navigation("AssessmentResponses");

                    b.Navigation("Blogs");

                    b.Navigation("Campaigns");

                    b.Navigation("ConsultantAppointments");

                    b.Navigation("Courses");

                    b.Navigation("Enrollments");

                    b.Navigation("MemberAppointments");
                });
#pragma warning restore 612, 618
        }
    }
}
